### ISSUE TITLE
Precision is lost when using matrices

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/Krylov.jl#126]
Precision is lost when using matrices.
```
A = rand(BigFloat, 3, 3)
A = A * A'
b = rand(BigFloat, 3)
x = cg(A, b)[1]
eltype(x)
```
returns `Float64`. I couldn't fix, because just adding types in `variants.jl` breaks other places.

**Comment by dpo** [comment]
Do you mean that if you wrap `A` into an operator, `x` has type `BigFloat`?

**Comment by abelsiqueira** [comment]
Yes. In part, the problem is [in this line](https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/master/src/variants.jl#L8).

**Comment by dpo** [comment]
Right, probably because the default type of a LinearOperator is Float64. That should be easy to fix.

**Comment by amontoison** [comment]
For the moment, we need to call `cg` and `cgls` with A already a `PreallocatedLinearOperator` if we want to them in multiple precision.

```julia
A = rand(BigFloat, 3, 3)
A = A * A'
op = PreallocatedLinearOperator(A)
b = rand(BigFloat, 3)
x = cg(op, b)[1]
eltype(x)
```
I wanted to use `PreallocatedLinearOperator` instead of this old `preallocated_LinearOperator` function but I had some problems with Integer matrices.
https://github.com/JuliaSmoothOptimizers/LinearOperators.jl/issues/82

**Comment by dpo** [comment]
That's right. It's because `PreallocatedLinearOperator` [captures the types](https://github.com/JuliaSmoothOptimizers/LinearOperators.jl/blob/master/src/PreallocatedLinearOperators.jl#L106). We simply need to change the call to `preallocated_LinearOperator` to a proper `PreallocatedLinearOperator{T,F1,F2,F3}(...)` or (simpler) to `PreallocatedLinearOperator(A)`. I would say that integer matrices are a fringe case for now and we can discuss them separately.

**Comment by amontoison** [comment]
Before we change the call to a proper `PreallocatedLinearOperator`, we need to have all methods also type stable in `Float32`. For the moment it's only the case for `CG` and `CGLS`.
I started to work on it two weeks ago : https://github.com/amontoison/Krylov.jl/commits/master
It's linked with the issue #103.

**Comment by amontoison** [comment]
@abelsiqueira Methods work in any floating-point data type with #134. Your update of `variants.jl` should work now.

**Comment by abelsiqueira** [comment]
Thanks, I'll try to take a look soon.
