### ISSUE TITLE
Add an option restart for FOM and GMRES

### ISSUE THREAD

**Issue by amontoison** [JuliaSmoothOptimizers/Krylov.jl#412]
Thanks to the Krylov solvers, it should be easy to have restarted variants `FOM(k)` and `GMRES(k)` now.

**Comment by geoffroyleconte** [comment]
Hi, could it be possible to have a restarted version of `GMRES`, `FOM` and `GPMR` by default? Since `gmres!`, `fom!` and `gpmr!` currently allocate vectors when the number of iterations is bigger than the memory size? Maybe it would be possible to add a boolean in the arguments of these function if you want to keep the current behaviour in some cases?

**Comment by amontoison** [comment]
Hi @geoffroyleconte !
I will work on it next week :smiley:
