### ISSUE TITLE
Solve matrix-matrix problem

### ISSUE THREAD

**Issue by vpuri3** [JuliaSmoothOptimizers/Krylov.jl#759]
I want to solve `Ax = y` for `K` unique RHSs. Wondering if I can stack them in a matrix and solve `A * X = Y` where `X, Y` are `N x K` matrices?

**Comment by amontoison** [comment]
Hi @vpuri3!
If `y` is a matrix, it's recommended to use a Block-Krylov method.
The issue is that we need to solve a `K x K` dense linear system at each iteration and I don't know how to support GPUs for this step with a generic implementation.

If I find a neat way to do that, I will add block-CG and block-GMRES.
